# Generated by Django 2.2.4 on 2019-08-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(default='singular', max_length=20),
            preserve_default=False,
        ),
    ]
